name: countdownmanager
description: A new Flutter project.

dependencies:
  flutter:
    sdk: flutter
  url_launcher: ^3.0.0
  intl: ^0.15.7
  shared_preferences: ^0.4.0

  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true
